using Content.Shared._Horizon.FlavorText;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        public Action<string>? OnFlavorTextChanged;

        // Horizon start
        public Action<int>? OnErpStatChanged;
        public Action<string>? OnOOCFlavorTextChanged;
        public Action<string>? OnERPFlavorTextChanged;
        // Horizon end

        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();
            CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
            CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();

            // Horizon start
            ERPStatusButton.OnItemSelected += args => OnErpStatChanged?.Invoke(args.Id);

            OOCFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("ooc-flavor-text-placeholder"));
            OOCFlavorTextInput.OnTextChanged += args => OnOOCFlavorTextChanged?.Invoke(Rope.Collapse(OOCFlavorTextInput.TextRope).Trim());

            ERPFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("erp-flavor-text-placeholder"));
            ERPFlavorTextInput.OnTextChanged += args => OnERPFlavorTextChanged?.Invoke(Rope.Collapse(ERPFlavorTextInput.TextRope).Trim());
            // Horizon end
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
        }
    }
}
