- type: startingGear
  id: CastawayGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    outerClothing: ClothingOuterHardsuitJetpackEVA
    head: ClothingHeadHelmetEVA
    shoes: ClothingShoesColorBlack
    back: EmergencyOxygenTankFilled
    id: CastawayPDA

- type: startingGear
  id: CastawayPodGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
    id: CastawayPDA

# Сценарий 1: в космосе с разбросаными вещами и шаттлом
- type: job
  id: CastawaySurvivor
  name: castaway-job-name-survivor
  description: castaway-job-description-survivor
  playTimeTracker: JobCastawaySurvivor
  setPreference: false
  startingGear: CastawayGear
  icon: "JobIconPassenger"

- type: playTimeTracker
  id: JobCastawaySurvivor

# Сценарий 2: Просыпается на заброшеной станции с разрушеным шаттлом
- type: job
  id: CastawaySleeper
  name: castaway-job-name-sleeper
  description: castaway-job-description-sleeper
  playTimeTracker: JobCastawaySleeper
  setPreference: false
  startingGear: CastawayPodGear
  icon: "JobIconPassenger"

- type: playTimeTracker
  id: JobCastawaySleeper
