using Content.Shared._Horizon._Fractions.AnCo.Companions;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Horizon._Fractions.AnCo.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CompanionUiFragment : BoxContainer
{
    private CompanionEntry? _selectedBorg;
    private readonly IEntityManager _entManager;

    public CompanionUiFragment()
    {
        _entManager = IoCManager.Resolve<IEntityManager>();
        RobustXamlLoader.Load(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        List<CompanionEntry> entry = new();
        UpdateState(entry);
    }

    public void Initialize()
    {
        BorgFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#202025"),
            BorderColor = Color.FromHex("#5a5a5a"),
            BorderThickness = new Thickness(2)
        };

        UpdateLoadState();
    }

    public void UpdateLoadState()
    {
        StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Компаньон:[/color] [color=yellow]инициализация[/color]"));
        BatteryLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Батарея:[/color] [color=yellow]инициализация[/color]"));
        MindLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Сознание:[/color] [color=yellow]инициализация[/color]"));
        ModulesLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Модулей:[/color] [color=yellow]инициализация[/color]"));
    }

    public void MissingData()
    {
        StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Компаньон:[/color] [color=red]данные не найдены[/color]"));
        BatteryLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Батарея:[/color] [color=red]данные не найдены[/color]"));
        MindLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Сознание:[/color] [color=red]данные не найдены[/color]"));
        ModulesLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Модулей:[/color] [color=red]данные не найдены[/color]"));
    }

    public void UpdateState(List<CompanionEntry> borgs)
    {
        // Очистка кнопок боргов
        CompanionListContainer.DisposeAllChildren();

        foreach (CompanionEntry borg in borgs)
        {
            var button = new Button
            {
                Text = borg.Name,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2)
            };

            button.OnPressed += _ =>
            {
                _selectedBorg = borg;
                UpdateSelectedDisplay();
            };

            CompanionListContainer.AddChild(button);
        }

        CommandButton.OnPressed += _ =>
        {
            this.RemoveAllChildren();
            this.AddChild(new CompanionCommandUiFragment());
        };

        // Выбираем борга по умолчанию
        if (_selectedBorg == null && borgs.Count > 0)
        {
            _selectedBorg = borgs[0];
        }

        UpdateSelectedDisplay();
    }

    private void UpdateSelectedDisplay()
    {
        if (_selectedBorg == null)
        {
            MissingData();
            return;
        }

        CompanionEntry b = (CompanionEntry)_selectedBorg;

        EntityUid ent = _entManager.GetEntity(b.Entity);
        CompanionSprite.SetEntity(ent);
        CompanionSprite.OverrideDirection = Direction.South;

        if (b.Name != null)
            StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive($"[color=gray]Компаньон:[/color] [color=white]{b.Name}[/color]"));
        else
            StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=gray]Компаньон:[/color] [color=white]данные не найдены[/color]"));

        if (b.currentCharge != null && b.maxCharge != null)
        {
            float maxCharge = (float)b.maxCharge;
            float currentCharge = (float)b.currentCharge;
            // Формула заряда батареи + защита деления на 0 (НА НОЛЬ ДЕЛИТЬ НЕЗЯ!!!)
            float battery = maxCharge > 0 ? (currentCharge / maxCharge) * 100f : 0;
            BatteryLabel.SetMessage(FormattedMessage.FromMarkupPermissive($"[color=gray]Батарея:[/color] [color=white]{battery}% ({currentCharge}/{maxCharge})[/color]"));
        }
        else
            BatteryLabel.SetMessage(FormattedMessage.FromMarkupPermissive($"[color=gray]Батарея:[/color] [color=red]батарея отсутствует[/color]"));

        if (b.mind != null)
            MindLabel.SetMessage(FormattedMessage.FromMarkupPermissive($"[color=gray]Сознание:[/color] [color=green]присутствует[/color]"));
        else
            MindLabel.SetMessage(FormattedMessage.FromMarkupPermissive($"[color=gray]Сознание:[/color] [color=red]отсутствует[/color]"));

        if (b.maxModules != null && b.modulesCount != null)
            ModulesLabel.SetMessage(FormattedMessage.FromMarkupPermissive($"[color=gray]Модулей:[/color] [color=white]{b.modulesCount}/{b.maxModules}[/color]"));
        else
            ModulesLabel.SetMessage(FormattedMessage.FromMarkupPermissive($"[color=gray]Модулей:[/color] [color=red]данные не найдены[/color]"));
    }
}
