using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Horizon._Fractions.AnCo.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CompanionCommandUiFragment : BoxContainer
{
    public CompanionCommandUiFragment()
    {
        RobustXamlLoader.Load(this);

        MainTabs.SetTabTitle(0, "Команды ИИ");
        MainTabs.SetTabTitle(1, "Фракции");
        MainTabs.SetTabTitle(2, "Воздействие");
        MainTabs.SetTabTitle(3, "Диагностика (ADM)");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
    }
}
