// SPDX-FileCopyrightText: 2025 ark1368
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Shared.Audio;

namespace Content.Shared._Crescent.ShipShields;

[RegisterComponent]
public sealed partial class ShipShieldEmitterComponent : Component
{
    public EntityUid? Shield;
    public EntityUid? Shielded;

    [DataField]
    public float Accumulator;

    /// <summary>
    /// Maximum hit points of the shield dome.
    /// </summary>
    [DataField]
    public float MaxHitPoints = 200f;

    /// <summary>
    /// Current hit points of the shield dome (runtime state).
    /// </summary>
    public float CurrentHitPoints;

    /// <summary>
    /// Duration of the cooldown in seconds when HP reaches 0.
    /// </summary>
    [DataField]
    public float CooldownDuration = 10f;

    /// <summary>
    /// Countdown timer for the cooldown period (runtime state).
    /// </summary>
    public float CooldownAccumulator;

    /// <summary>
    /// Whether the shield is currently on cooldown after being destroyed.
    /// </summary>
    public bool OnCooldown;

    /// <summary>
    /// HP regenerated per second after the regen delay has elapsed.
    /// </summary>
    [DataField]
    public float RegenPerSecond = 10f;

    /// <summary>
    /// Seconds without taking damage before HP regeneration begins.
    /// </summary>
    [DataField]
    public float RegenDelay = 30f;

    /// <summary>
    /// Tracks how many seconds have passed since the last damage was received (runtime state).
    /// </summary>
    public float TimeSinceLastDamage;

    /// <summary>
    /// The color of the shield generated by this emitter.
    /// </summary>
    [DataField]
    public Color ShieldColor = Color.White;

    /// <summary>
    /// On power up, players for all on vessel, pitched down.
    /// </summary>
    [DataField]
    public SoundSpecifier PowerUpSound = new SoundPathSpecifier("/Audio/Effects/teleport_arrival.ogg");

    [DataField]
    public SoundSpecifier PowerDownSound = new SoundPathSpecifier("/Audio/Effects/teleport_departure.ogg");
}
